apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: psoz2e158-python 
  janus-idp.io/tekton: psoz2e158-python
  backstage.io/kubernetes-id: psoz2e158-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: psoz2e158-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml