apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: psoz2e158-python
  janus-idp.io/tekton: psoz2e158-python
  backstage.io/kubernetes-id: psoz2e158-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: psoz2e158-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
