apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: psoz2e158-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: psoz2e158-python 
  name: psoz2e158-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: psoz2e158-python 
